service: health-cron
provider:
  name: aws
  runtime: nodejs12.x
functions:
  checkSite:
    handler: handler.checkSite
    events:
      - http:
         path: checkSite
         method: get
    environment:
      WEBSITE_NAME: 'graphleads'
      WEBSITE_URL: 'https://www.udacity.com/'
      SUCCESS_MSG: 'Website is up and returns html'
      SLACK_WEBHOOK: 'https://hooks.slack.com/services/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'

plugins:
  - serverless-offline
